apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: nginx-ingress-controller
  name: nginx-ingress-controller
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http-stats
    port: 18080
    protocol: TCP
    targetPort: 18080
  selector:
    k8s-app: nginx-ingress-lb
  #type: NodePort
  # For Production purpose uncomment the line bellow 
  # and comment the line above to create and ELB
  type: LoadBalancer
  
